[phases.setup]
nixPkgs = ["...", "postgresql"]

[phases.build]
cmds = ["bundle install", "bundle exec bootsnap precompile --gemfile"]

[phases.start]
cmd = "bundle exec rails db:prepare && bundle exec rails assets:precompile && bundle exec rails server -b 0.0.0.0 -p $PORT"

[variables]
RAILS_ENV = "production"
RAILS_LOG_TO_STDOUT = "1"
RAILS_SERVE_STATIC_FILES = "1"