[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/up"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "./bin/rails server -b 0.0.0.0"

[environments.production]
variables = { RAILS_ENV = "production", RAILS_LOG_TO_STDOUT = "1", RAILS_SERVE_STATIC_FILES = "1" }

[environments.production.services.sgt-backend]
source = "."